/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus A455L
 */
public class posttest2 extends javax.swing.JFrame {

    /**
     * Creates new form posttest2
     */
    public posttest2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JLProvinsi = new javax.swing.JLabel();
        JLNik = new javax.swing.JLabel();
        JLNama = new javax.swing.JLabel();
        JLTtl = new javax.swing.JLabel();
        JLJenisKelamin = new javax.swing.JLabel();
        JLAlamat = new javax.swing.JLabel();
        JLRt = new javax.swing.JLabel();
        JLDesa = new javax.swing.JLabel();
        JLKecamatan = new javax.swing.JLabel();
        JLAgama = new javax.swing.JLabel();
        JLKawin = new javax.swing.JLabel();
        JLKerja = new javax.swing.JLabel();
        JLWarga = new javax.swing.JLabel();
        JLBerlaku = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTHasil = new javax.swing.JTextArea();
        TFNik = new javax.swing.JTextField();
        TFNama = new javax.swing.JTextField();
        TFTtl = new javax.swing.JTextField();
        TFAlamat = new javax.swing.JTextField();
        TFRt = new javax.swing.JTextField();
        TFDesa = new javax.swing.JTextField();
        TFKec = new javax.swing.JTextField();
        TFPekerjaan = new javax.swing.JTextField();
        TFBerlaku = new javax.swing.JTextField();
        JLGol = new javax.swing.JLabel();
        JLKab = new javax.swing.JLabel();
        JCTanggal = new javax.swing.JComboBox<>();
        JCBulan = new javax.swing.JComboBox<>();
        JCTahun = new javax.swing.JComboBox<>();
        JCGol = new javax.swing.JComboBox<>();
        JCAgama = new javax.swing.JComboBox<>();
        JCKawin = new javax.swing.JComboBox<>();
        JCWarga = new javax.swing.JComboBox<>();
        JRLaki = new javax.swing.JRadioButton();
        JRPerempuan = new javax.swing.JRadioButton();
        JBKeluar = new javax.swing.JButton();
        JBProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        JLProvinsi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLProvinsi.setText("PROVINSI KALIMANTAN TIMUR");

        JLNik.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLNik.setText("NIK");

        JLNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLNama.setText("Nama ");

        JLTtl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLTtl.setText("Tempat/Tgl Lahir");

        JLJenisKelamin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLJenisKelamin.setText("Jenis Kelamin");

        JLAlamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLAlamat.setText("Alamat");

        JLRt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLRt.setText("RT / RW");

        JLDesa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLDesa.setText("Kel / Desa");

        JLKecamatan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLKecamatan.setText("Kecamatan");

        JLAgama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLAgama.setText("Agama");

        JLKawin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLKawin.setText("Status Perkawinan");

        JLKerja.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLKerja.setText("Pekerjaan");

        JLWarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLWarga.setText("Kewarganegaraan");

        JLBerlaku.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLBerlaku.setText("Berlaku Hingga");

        JTHasil.setColumns(20);
        JTHasil.setRows(5);
        jScrollPane1.setViewportView(JTHasil);

        JLGol.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        JLGol.setText("Gol. Darah :");

        JLKab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLKab.setText("KABUPATEN KUTAI KARTANEGARA");

        JCTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        JCTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCTanggalActionPerformed(evt);
            }
        });

        JCBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        JCBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBulanActionPerformed(evt);
            }
        });

        JCTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "19990" }));
        JCTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCTahunActionPerformed(evt);
            }
        });

        JCGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "A", "B", "AB", "O" }));
        JCGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCGolActionPerformed(evt);
            }
        });

        JCAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Islam", "Katolik", "Protestan", "Hindu", "Budha", "Lain-Lain" }));
        JCAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCAgamaActionPerformed(evt);
            }
        });

        JCKawin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kawin", "Belum Kawin" }));
        JCKawin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCKawinActionPerformed(evt);
            }
        });

        JCWarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "WNA", "WNI" }));
        JCWarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCWargaActionPerformed(evt);
            }
        });

        buttonGroup1.add(JRLaki);
        JRLaki.setText("Laki - Laki");

        buttonGroup1.add(JRPerempuan);
        JRPerempuan.setText("Perempuan");

        JBKeluar.setText("KELUAR");
        JBKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKeluarActionPerformed(evt);
            }
        });

        JBProses.setText("PROSES");
        JBProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(JLProvinsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(JLKab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(JLKerja)
                        .addGap(96, 96, 96)
                        .addComponent(TFPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(376, 376, 376)
                        .addComponent(JBKeluar)
                        .addGap(119, 119, 119)
                        .addComponent(JBProses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(JLWarga)
                        .addGap(59, 59, 59)
                        .addComponent(JCWarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(JLBerlaku)
                        .addGap(69, 69, 69)
                        .addComponent(TFBerlaku, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLNik, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLNama, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLTtl)
                            .addComponent(JLJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLAgama)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLRt)
                                    .addComponent(JLDesa)
                                    .addComponent(JLKecamatan)))
                            .addComponent(JLKawin))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCKawin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFNik, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFRt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFDesa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFKec, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRLaki)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRPerempuan)
                                                .addGap(39, 39, 39)
                                                .addComponent(JLGol)))
                                        .addGap(29, 29, 29)
                                        .addComponent(JCGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TFTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JCTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JCBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JCTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JCAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JLProvinsi)
                .addGap(3, 3, 3)
                .addComponent(JLKab, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(JLNik)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JLNama)
                                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JLTtl)
                                    .addComponent(TFTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(JLJenisKelamin)
                                .addGap(15, 15, 15)
                                .addComponent(JLAlamat)
                                .addGap(24, 24, 24)
                                .addComponent(JLRt)
                                .addGap(17, 17, 17)
                                .addComponent(JLDesa)
                                .addGap(17, 17, 17)
                                .addComponent(JLKecamatan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JRLaki)
                                    .addComponent(JRPerempuan)
                                    .addComponent(JLGol)
                                    .addComponent(JCGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(TFRt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFDesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(JLAgama))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JCAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLKawin)
                    .addComponent(JCKawin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLKerja))
                    .addComponent(TFPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBKeluar)
                    .addComponent(JBProses))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLWarga))
                    .addComponent(JCWarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JLBerlaku))
                    .addComponent(TFBerlaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCTanggalActionPerformed
        // TODO add your handling code here:
        JCTanggal.getSelectedItem();
    }//GEN-LAST:event_JCTanggalActionPerformed

    private void JCBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBulanActionPerformed
        // TODO add your handling code here:
        JCBulan.getSelectedItem();
    }//GEN-LAST:event_JCBulanActionPerformed

    private void JCTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCTahunActionPerformed
        // TODO add your handling code here:
        JCTahun.getSelectedItem();
    }//GEN-LAST:event_JCTahunActionPerformed

    private void JCGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCGolActionPerformed
        // TODO add your handling code here:
        JCGol.getSelectedItem();
    }//GEN-LAST:event_JCGolActionPerformed

    private void JBProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProsesActionPerformed
        // TODO add your handling code here:
        String prov =            JLProvinsi.getText();
        String nik =             JLNik.getText();
        String nama =            JLNama.getText();
        String rt =              JLRt.getText();
        String alamat =          JLAlamat.getText();
        String berlaku =         JLBerlaku.getText();
        String desa =            JLDesa.getText();
        String tempat =          TFTtl.getText();
        String kec =             JLKecamatan.getText();
        String kab =             JLKab.getText();
        String pekerjaan =       JLKerja.getText();
        String kewarganegaraan = JLWarga.getText();
        String agama =           JCAgama.getSelectedItem().toString();
        String status =          JCKawin.getSelectedItem().toString();
        String tanggal =         JCTanggal.getSelectedItem().toString();
        String bulan =           JCBulan.getSelectedItem().toString();
        String tahun =           JCTahun.getSelectedItem().toString();
        String gol =             JCGol.getSelectedItem().toString();
        
        String JenisKelamin = null;
        if (JRLaki.isSelected())
            JenisKelamin = JRLaki.getText();
        else if (JRPerempuan.isSelected())
            JenisKelamin = JRPerempuan.getText();
        
        JTHasil.setText("\t             "+prov+"\n\t        "+kab+"\nNIK : "+nik+"\nNama : "+nama+"\nTempat Lahir : "+tempat+"  "+tanggal+"  "+bulan+"  "+tahun+"\nJenis Kelamin : "+JenisKelamin+"\tGolongan Darah : "+gol+"\nAlamat : "+alamat+"\n      RT / RW : "+rt+"\n      Kel / Desa : "+desa+"\n      Kecamata : "+kec+"\nAgama : "+agama+"\nStatus Perkawinan : "+status+"\nPekerjaan : "+pekerjaan+"\nKewarganegaraan : "+kewarganegaraan+"\nBerlaku Hingga : "+berlaku);
    }//GEN-LAST:event_JBProsesActionPerformed

    private void JCAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCAgamaActionPerformed
        // TODO add your handling code here:
        JCAgama.getSelectedItem();
    }//GEN-LAST:event_JCAgamaActionPerformed

    private void JCKawinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCKawinActionPerformed
        // TODO add your handling code here:
        JCKawin.getSelectedItem();
    }//GEN-LAST:event_JCKawinActionPerformed

    private void JCWargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCWargaActionPerformed
        // TODO add your handling code here:
        JCWarga.getSelectedItem();
    }//GEN-LAST:event_JCWargaActionPerformed

    private void JBKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JBKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new posttest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBKeluar;
    private javax.swing.JButton JBProses;
    private javax.swing.JComboBox<String> JCAgama;
    private javax.swing.JComboBox<String> JCBulan;
    private javax.swing.JComboBox<String> JCGol;
    private javax.swing.JComboBox<String> JCKawin;
    private javax.swing.JComboBox<String> JCTahun;
    private javax.swing.JComboBox<String> JCTanggal;
    private javax.swing.JComboBox<String> JCWarga;
    private javax.swing.JLabel JLAgama;
    private javax.swing.JLabel JLAlamat;
    private javax.swing.JLabel JLBerlaku;
    private javax.swing.JLabel JLDesa;
    private javax.swing.JLabel JLGol;
    private javax.swing.JLabel JLJenisKelamin;
    private javax.swing.JLabel JLKab;
    private javax.swing.JLabel JLKawin;
    private javax.swing.JLabel JLKecamatan;
    private javax.swing.JLabel JLKerja;
    private javax.swing.JLabel JLNama;
    private javax.swing.JLabel JLNik;
    private javax.swing.JLabel JLProvinsi;
    private javax.swing.JLabel JLRt;
    private javax.swing.JLabel JLTtl;
    private javax.swing.JLabel JLWarga;
    private javax.swing.JRadioButton JRLaki;
    private javax.swing.JRadioButton JRPerempuan;
    private javax.swing.JTextArea JTHasil;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFBerlaku;
    private javax.swing.JTextField TFDesa;
    private javax.swing.JTextField TFKec;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNik;
    private javax.swing.JTextField TFPekerjaan;
    private javax.swing.JTextField TFRt;
    private javax.swing.JTextField TFTtl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
